<div class="bg-white p-6 rounded-xl shadow-md max-w-lg mx-auto">
    <h2 class="text-xl font-semibold mb-6 border-b pb-4"><?= e($title); ?></h2>
    <form action="<?= APP_URL; ?>/order-categories/store" method="POST">
        <div>
            <label for="name" class="block text-sm font-medium text-gray-700 mb-1">نام دسته‌بندی</label>
            <input type="text" name="name" id="name" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
        </div>
        <div class="mt-8 pt-5 border-t flex justify-end">
            <a href="<?= APP_URL; ?>/order-categories" class="bg-gray-200 text-gray-700 font-bold py-2 px-6 rounded-lg hover:bg-gray-300 ml-4">انصراف</a>
            <button type="submit" class="bg-blue-600 text-white font-bold py-2 px-6 rounded-lg hover:bg-blue-700">ذخیره</button>
        </div>
    </form>
</div>
